source "https://rubygems.org"

gem 'puma'
gem 'sinatra'
gem 'sinatra-cross_origin'
gem 'activerecord'
gem 'activerecord-postgis-adapter'
gem 'activesupport'
gem 'sinatra-activerecord'
gem 'pg'
gem 'json'
gem 'rake'

group :development, :test do
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
  gem 'sqlite3'
  gem 'database_cleaner'
end
